In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [4]:
ar = np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
a = [2,3,4]

In [9]:
np.asanyarray(a)

array([2, 3, 4])

In [10]:
b = np.matrix(l)

In [12]:
b              #metrix bydefault 2-D

matrix([[1, 2, 3, 4]])

In [13]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [14]:
a = np.array(l)

In [15]:
c=a

In [16]:
c

array([1, 2, 3, 4])

In [17]:
a

array([1, 2, 3, 4])

In [18]:
type(c)

numpy.ndarray

In [19]:
type(a)

numpy.ndarray

In [20]:
c[0]

np.int64(1)

In [22]:
c[0]=100

In [23]:
c

array([100,   2,   3,   4])

In [25]:
a          # both variables points on same address ahallow copy concept

array([100,   2,   3,   4])

In [32]:
d= np.copy(a)     #deep copy not a shallow copy

In [33]:
d

array([100, 400,   3,   4])

In [34]:
a

array([100, 400,   3,   4])

In [38]:
a[1]=600

In [39]:
a

array([100, 600,   3,   4])

In [40]:
d

array([100, 400,   3,   4])

In [41]:
#Data generating 

In [42]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [43]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
np.fromiter(b)

In [44]:
np.fromstring('1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30',sep=" ")

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30.])

In [45]:
#datatypes

In [46]:
l = [2,3,4,5,6]

In [48]:
arr = np.array(l)

In [49]:
arr.ndim

1

In [50]:
ar2 = np.array([[1,2,3,4],[2,3,4,5]])

In [51]:
ar2.ndim

2

In [52]:
ar.size

4

In [53]:
ar2.size

8

In [54]:
ar.shape

(4,)

In [55]:
ar2.shape

(2, 4)

In [56]:
ar.dtype

dtype('int64')

In [57]:
ar2.dtype

dtype('int64')

In [59]:
ar2 = np.array([[1, 2.0, 3, 4],
       [2, 3, 4, 5]])

In [60]:
ar2.dtype

dtype('float64')

In [61]:
range(5)

range(0, 5)

In [62]:
list(range(5))

[0, 1, 2, 3, 4]

In [66]:
list(np.arange(2,11,0.1))

[np.float64(2.0),
 np.float64(2.1),
 np.float64(2.2),
 np.float64(2.3000000000000003),
 np.float64(2.4000000000000004),
 np.float64(2.5000000000000004),
 np.float64(2.6000000000000005),
 np.float64(2.7000000000000006),
 np.float64(2.8000000000000007),
 np.float64(2.900000000000001),
 np.float64(3.000000000000001),
 np.float64(3.100000000000001),
 np.float64(3.200000000000001),
 np.float64(3.300000000000001),
 np.float64(3.4000000000000012),
 np.float64(3.5000000000000013),
 np.float64(3.6000000000000014),
 np.float64(3.7000000000000015),
 np.float64(3.8000000000000016),
 np.float64(3.9000000000000017),
 np.float64(4.000000000000002),
 np.float64(4.100000000000001),
 np.float64(4.200000000000002),
 np.float64(4.3000000000000025),
 np.float64(4.400000000000002),
 np.float64(4.500000000000002),
 np.float64(4.600000000000002),
 np.float64(4.700000000000003),
 np.float64(4.8000000000000025),
 np.float64(4.900000000000002),
 np.float64(5.000000000000003),
 np.float64(5.100000000000003),
 np.

In [69]:
list(np.arange(2.3,5.6,.3))

[np.float64(2.3),
 np.float64(2.5999999999999996),
 np.float64(2.8999999999999995),
 np.float64(3.1999999999999993),
 np.float64(3.499999999999999),
 np.float64(3.799999999999999),
 np.float64(4.099999999999999),
 np.float64(4.399999999999999),
 np.float64(4.699999999999998),
 np.float64(4.999999999999998),
 np.float64(5.299999999999998)]

In [72]:
np.linspace(2,20,10)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [76]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [79]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [78]:
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [82]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [85]:
on = np.ones((2,3,2))

In [86]:
on*5

array([[[5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.]]])

In [89]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [90]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [92]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [94]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [95]:
np.random.randn(6,5)

array([[ 0.63502908, -0.64332638,  0.75163704, -0.76639035, -0.05028046],
       [ 1.11772879,  1.48781161,  1.07105778,  0.09135393, -0.19085954],
       [ 0.01172126,  1.21480137, -1.21344633,  1.97427728,  1.2391565 ],
       [ 1.0066052 , -1.0580561 , -0.26324952, -0.97509204,  2.22325608],
       [ 0.61649095, -1.29901408,  0.62881066, -0.30549592,  0.6591266 ],
       [ 0.31448899, -0.26861215,  1.56510443,  0.41664224,  1.28829996]])

In [96]:
import pandas as pd

In [99]:
arr = np.random.randn(4,4)

In [100]:
pd.DataFrame(arr)


0         1         2         3
0  0.350891 -0.512572  0.727360 -0.031560
1  0.656664 -0.665869  0.099831 -1.350241
2 -1.036684  0.288930 -0.321212 -0.189686
3  0.277222  1.142400 -0.719163 -0.551477

In [103]:
np.random.rand(3,4)

array([[0.85084869, 0.44571175, 0.28267548, 0.01929905],
       [0.67420315, 0.78595858, 0.69352886, 0.09620613],
       [0.73842787, 0.68332314, 0.27016627, 0.26832532]])

In [106]:
np.random.randint(1,100,(5,5))

array([[ 1, 68, 77,  7, 43],
       [29, 54, 60, 62, 72],
       [ 3, 95, 50, 17, 95],
       [79,  1, 69, 10, 81],
       [50, 53, 86, 36, 32]])

In [108]:
pd.DataFrame(np.random.randint(1,20,(300,400))).to_csv('test.csv')

In [110]:
arr = np.random.rand(3,4)

In [114]:
arr1 = arr.reshape(6,2)

In [117]:
arr1

array([[0.96390932, 0.63718292],
       [0.02926352, 0.09860181],
       [0.72981207, 0.0278308 ],
       [0.37580529, 0.5626992 ],
       [0.45531764, 0.7249607 ],
       [0.06845924, 0.90121416]])

In [118]:
arr1[3]

array([0.37580529, 0.5626992 ])

In [121]:
arr1[3][1]

np.float64(0.5626992009577285)

In [122]:
arr1

array([[0.96390932, 0.63718292],
       [0.02926352, 0.09860181],
       [0.72981207, 0.0278308 ],
       [0.37580529, 0.5626992 ],
       [0.45531764, 0.7249607 ],
       [0.06845924, 0.90121416]])

In [129]:
arr1[2:6]

array([[0.72981207, 0.0278308 ],
       [0.37580529, 0.5626992 ],
       [0.45531764, 0.7249607 ],
       [0.06845924, 0.90121416]])

In [130]:
arr1[2:6,1]

array([0.0278308 , 0.5626992 , 0.7249607 , 0.90121416])

In [1]:
import numpy as np
arr = np.random.randint(1,100,(5,5))

In [2]:
arr

array([[ 6, 57, 88, 29, 86],
       [29, 60, 31, 74,  6],
       [73, 94, 30, 66, 81],
       [99, 20, 71, 55,  2],
       [42, 84, 75, 85, 10]])

In [136]:
arr[arr>50]

array([79, 90, 51, 86, 71, 91, 88, 96, 69, 51, 84, 88])

In [6]:
arr[2:4,[1,2]]

array([[94, 30],
       [20, 71]])

In [8]:
arr[0][0]=500

In [9]:
arr

array([[500,  57,  88,  29,  86],
       [ 29,  60,  31,  74,   6],
       [ 73,  94,  30,  66,  81],
       [ 99,  20,  71,  55,   2],
       [ 42,  84,  75,  85,  10]])

In [11]:
arr1=np.random.randint(1,3,(3,3))

In [12]:
arr2 = np.random.randint(1,3,(3,3))

In [13]:
arr1+arr2

array([[3, 4, 4],
       [2, 4, 3],
       [2, 3, 2]])

In [14]:
arr1*arr2

array([[2, 4, 4],
       [1, 4, 2],
       [1, 2, 1]])

In [15]:
arr1-arr2

array([[-1,  0,  0],
       [ 0,  0,  1],
       [ 0,  1,  0]])

In [16]:
arr1/arr2

array([[0.5, 1. , 1. ],
       [1. , 1. , 2. ],
       [1. , 2. , 1. ]])

In [17]:
arr1.dot(arr2)

array([[6, 8, 6],
       [6, 8, 6],
       [5, 7, 5]])

In [18]:
arr1@arr2

array([[6, 8, 6],
       [6, 8, 6],
       [5, 7, 5]])

In [19]:
arr/0

/tmp/ipykernel_1782/4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [20]:
arr1+100

array([[101, 102, 102],
       [101, 102, 102],
       [101, 102, 101]])

In [21]:
arr1

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 1]])

In [22]:
arr1**2

array([[1, 4, 4],
       [1, 4, 4],
       [1, 4, 1]])

In [23]:
# broadcasting

In [25]:
arr = np.zeros((4,4))

In [26]:
row = np.array([1,2,3,4])

In [27]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [33]:
row.shape

(4,)

In [36]:
arr2 = row.reshape(4,1)

In [38]:
arr+arr2

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [40]:
col = np.array([[1,2,3,4]])

In [42]:
arr = np.zeros((4,4))

In [43]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [45]:
arr1 = np.random.randint(1,4,(3,4))

In [48]:
arr2 = arr1**2

In [49]:
arr2

array([[1, 1, 1, 1],
       [9, 9, 4, 9],
       [4, 1, 1, 9]])

In [47]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.        , 1.        ],
       [1.73205081, 1.73205081, 1.41421356, 1.73205081],
       [1.41421356, 1.        , 1.        , 1.73205081]])

In [50]:
np.sqrt(arr2)

array([[1., 1., 1., 1.],
       [3., 3., 2., 3.],
       [2., 1., 1., 3.]])

In [51]:
np.exp(arr1)

array([[ 2.71828183,  2.71828183,  2.71828183,  2.71828183],
       [20.08553692, 20.08553692,  7.3890561 , 20.08553692],
       [ 7.3890561 ,  2.71828183,  2.71828183, 20.08553692]])

In [52]:
np.log(arr1)

array([[0.        , 0.        , 0.        , 0.        ],
       [1.09861229, 1.09861229, 0.69314718, 1.09861229],
       [0.69314718, 0.        , 0.        , 1.09861229]])

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,4))

In [3]:
arr

array([[9, 3, 2, 8],
       [6, 5, 9, 9],
       [2, 7, 6, 1]])

In [4]:
arr.reshape(2,6)

array([[9, 3, 2, 8, 6, 5],
       [9, 9, 2, 7, 6, 1]])

In [5]:
arr.reshape(2,-6)

array([[9, 3, 2, 8, 6, 5],
       [9, 9, 2, 7, 6, 1]])

In [6]:
arr.T

array([[9, 6, 2],
       [3, 5, 7],
       [2, 9, 6],
       [8, 9, 1]])

In [7]:
arr.flatten()

array([9, 3, 2, 8, 6, 5, 9, 9, 2, 7, 6, 1])

In [8]:
arr1 = np.array([1,2,3,3,4])

In [9]:
arr1.ndim

1

In [11]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 3, 4]])

In [12]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [13]:
arr

array([[9, 3, 2, 8],
       [6, 5, 9, 9],
       [2, 7, 6, 1]])

In [14]:
np.squeeze(arr)

array([[9, 3, 2, 8],
       [6, 5, 9, 9],
       [2, 7, 6, 1]])

In [15]:
data = np.array([[1],[2],[3]])

In [16]:
np.squeeze(data)

array([1, 2, 3])

In [17]:
arr1

array([1, 2, 3, 3, 4])

In [18]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [19]:
np.roll(arr1,shift=2)

array([3, 4, 1, 2, 3])

In [20]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [21]:
arr1 = np.random.randint(1,10,(3,4))

In [22]:
arr2 = np.random.randint(1,10,(3,4))

In [23]:
arr1

array([[6, 6, 7, 6],
       [8, 2, 1, 8],
       [1, 8, 2, 6]])

In [24]:
arr2

array([[6, 8, 5, 7],
       [8, 3, 6, 7],
       [3, 9, 9, 9]])

In [25]:
arr1+arr2

array([[12, 14, 12, 13],
       [16,  5,  7, 15],
       [ 4, 17, 11, 15]])

In [26]:
arr1*arr2

array([[36, 48, 35, 42],
       [64,  6,  6, 56],
       [ 3, 72, 18, 54]])

In [27]:
arr1/arr2

array([[1.        , 0.75      , 1.4       , 0.85714286],
       [1.        , 0.66666667, 0.16666667, 1.14285714],
       [0.33333333, 0.88888889, 0.22222222, 0.66666667]])

In [30]:
arr1%arr2

array([[0, 6, 2, 6],
       [0, 2, 1, 1],
       [1, 8, 2, 6]])

In [32]:
arr1 & arr2

array([[6, 0, 5, 6],
       [8, 2, 0, 0],
       [1, 8, 0, 0]])

In [33]:
~arr1

array([[-7, -7, -8, -7],
       [-9, -3, -2, -9],
       [-2, -9, -3, -7]])

In [34]:
~arr2

array([[ -7,  -9,  -6,  -8],
       [ -9,  -4,  -7,  -8],
       [ -4, -10, -10, -10]])

In [35]:
arr1|arr2

array([[ 6, 14,  7,  7],
       [ 8,  3,  7, 15],
       [ 3,  9, 11, 15]])

In [36]:
arr1>arr2

array([[False, False,  True, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [37]:
#np string function

In [39]:
arr = np.array(['aman','uddin'])

In [40]:
np.char.upper(arr)

array(['AMAN', 'UDDIN'], dtype='<U5')

In [41]:
np.char.title(arr)

array(['Aman', 'Uddin'], dtype='<U5')

In [42]:
np.char.capitalize(arr)

array(['Aman', 'Uddin'], dtype='<U5')

In [43]:
#mathemarical functions

In [44]:
#sorting searching and counting functions

In [45]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [46]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [47]:
np.searchsorted(arr,34)

np.int64(12)

In [48]:
arr1 = np.array([0,345,454,0,0,0,0,0])

In [49]:
np.count_nonzero(arr1)

2

In [50]:
np.where(arr>6)

(array([5, 8]),)

In [51]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [54]:
np.extract(arr>3,arr)

array([  4,   4,   5,   6,  72, 455,   5,   6,   6])

In [55]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [56]:
arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616,   432345564227567616])

In [57]:
#copy and swaps

In [59]:
a= np.copy(arr)   #deep copy

In [67]:
b = arr.view()   #shallow copy

In [68]:
b[0]

np.int64(69)

In [72]:
b[0]=100

In [73]:
b

array([100,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [74]:
arr

array([100,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])